### ISSUE TITLE
load BurpExtender error

### ISSUE THREAD

**Issue by nmweizi** [NetSPI/BurpExtractor#1]
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.y3e.a(Unknown Source)
	at burp.y3e.<init>(Unknown Source)
	at burp.fme.a(Unknown Source)
	at burp.q0h.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by wstrei** [comment]
Hey nmweizi,

Looks like you probably compiled this yourself because I failed to include a JAR in the release (my bad). I added a new release which has the JAR attached. Please give that a shot and see if it works for you.

**Comment by nmweizi** [comment]
@wstrei 
hi,is fine.thx
